version: "3"
services:
  mirror_steuer:
    container_name: mirror_steuer
    environment:
        TZ: "Europe/Berlin"
    build: .
    restart: always
    ports:
      - "8081:80"
    volumes:
      - ${ALL_SOURCES}
      # - ${STEUER_SETTINGS_MOUNT}
      # - ${STEUER_CONFIG_MOUNT}

  mirror_magic:
    container_name: mirror_magic
    image: karsten13/magicmirror:latest
    ports:
      - "8082:8080"
    volumes:
      - ${MM_MODULES_MOUNT}
      - ${MM_CONFIG_MOUNT}
    restart: unless-stopped
    command: >
      sh -c "cd modules/MMM-Remote-Control && npm install && cd ../.. && npm run server"










