version: "3"
services:
  # mirror_on_the_wall:
  #   container_name: mirror_steuer
  #   environment:
  #       TZ: "Europe/Berlin"
  #   build: .
  #   restart: always
  #   ports:
  #     - "8081:80"


  magic_mirror:
    container_name: mirror_magic
    image: karsten13/magicmirror:latest
    ports:
      - "8082:8080"
    volumes:
      - ${MM_MODULES_MOUNT}
      - ${MM_CONFIG_MOUNT}
    restart: unless-stopped
    command: 
      - npm
      - run
      - server





